---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Create test files
      ansible.builtin.file:
        path: "{{ item }}/cleanup-test-file"
        state: touch
        mode: "0644"
      loop:
        - /tmp
        - /srv/cleanup-volume
        - /var/tmp
